CREATE TABLE MY_DATA(
    ID NUMBER(4),
    NAME VARCHAR2(10),
    USERID VARCHAR2(30),
    SALARY NUMBER(10,2),
    PRIMARY KEY(ID));
SELECT * FROM MY_DATA;
INSERT INTO MY_DATA VALUES(1, 'SCOTT', 'SSCOTT', 10000);
INSERT INTO MY_DATA VALUES(2, 'FORD', 'FFORD', 13000);
INSERT INTO MY_DATA VALUES(3, 'PATEL', 'PPATEL', 33000);
INSERT INTO MY_DATA VALUES(4, 'REPORT', 'RREPORT', 23500);
INSERT INTO MY_DATA VALUES(5, 'GOOD', 'GGOOD', 44450);
SELECT * FROM MY_DATA;
DESC MY_DATA;
COMMIT;

UPDATE MY_DATA SET SALARY=65000 WHERE ID=3;
COMMIT;

DELETE FROM MY_DATA WHERE LOWER(NAME)='ford';

UPDATE MY_DATA SET SALARY=15000 WHERE SALARY<=15000;

DROP TABLE MY_DATA;

DROP TABLE BOOK;

DROP TABLE BOOK;
DROP TABLE BOOKKIND;
CREATE TABLE BOOKKIND(
    BOOKCODE NUMBER(4),
    BOOKKIND VARCHAR2(20) NOT NULL,
    LOC VARCHAR2(17) NOT NULL,
    PRIMARY KEY(BOOKCODE));
CREATE TABLE BOOK(
    BOOKCODE NUMBER(4) NOT NULL,
    BOOKID VARCHAR2(12),
    BOOKNAME VARCHAR2(60) NOT NULL,
    PUBLISHER VARCHAR2(30) NOT NULL,
    PUBYEAR NUMBER(4) DEFAULT TO_CHAR(SYSDATE,'YYYY'),
    PRIMARY KEY(BOOKID),
    FOREIGN KEY(BOOKCODE) REFERENCES BOOKKIND(BOOKCODE));
DESC BOOK;

INSERT INTO BOOKKIND VALUES(100, '철학', '3층 인문실');
INSERT INTO BOOKKIND VALUES(200, '인문', '3층 인문실');
INSERT INTO BOOKKIND VALUES(300, '자연과학', '4층 과학실');
INSERT INTO BOOKKIND VALUES(400, 'IT', '4층 과학실');
SELECT * FROM  BOOKKIND;

INSERT INTO BOOK VALUES(100,'100A01','철학자의 삶', '더존출판', 2017);
INSERT INTO BOOK VALUES(400,'400A01','이것이 DB다', '더존출판', 2018);
INSERT INTO BOOK VALUES(NULL,'200A01','철학자의 삶', '더존출판', 2017);
SELECT * FROM BOOK;
