COMMIT;
SELECT * FROM DEPT01;
DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
SELECT * FROM DEPT01;
DELETE FROM DEPT01 WHERE DEPTNO=40;
SELECT * FROM DEPT01;
COMMIT;
ROLLBACK;
DELETE FROM DEPT01 WHERE DEPTNO=30;
SELECT * FROM DEPT01;
SAVEPOINT C1; --C1 =10, 20
DELETE FROM DEPT01 WHERE DEPTNO=20;
SELECT * FROM DEPT01;
SAVEPOINT C2; --C2 =10
DELETE FROM DEPT01;
SELECT * FROM DEPT01; --ALL DELETE
ROLLBACK TO C2;
SELECT * FROM DEPT01;
ROLLBACK TO C1;
SELECT * FROM DEPT01;